package site

import (
	"encoding/json"
	"fmt"
	"html/template"
	"strings"
	"time"

	"github.com/bluesky-social/indigo/atproto/syntax"
)

const CollectionDocument = CollectionBase + ".document"

// Document may be standalone or associated with a [Publication].
// This [Record] can be used to store a document's content and its associated metadata.
type Document struct {
	// Site points to a [Publication] record `at://` or a [Publication.URL] `https://` for loose documents.
	// Avoid trailing slashes.
	Site *URL `json:"site" map:"string"`
	// Title of the [Document].
	// Max length: 5000.
	// Max graphemes: 500.
	Title string `json:"title"`
	// PublishedAt is the [time.Time] of the [Document]'s publish time.
	PublishedAt time.Time `json:"-"`
	// Path is combined with [Document.Site] or [Publication.URL] to construct a canonical URL to the document.
	// A slash should be included at the beginning of this value.
	Path *string `json:"path,omitempty"`
	// A brief Description or excerpt from the [Document].
	// Max length: 30000.
	// Max graphemes: 3000.
	Description *string `json:"description,omitempty"`
	// CoverImage to used for thumbnail or cover.
	// Less than 1MB in size.
	CoverImage *Blob `json:"coverImage,omitempty"`
	// Content is a custom [Record] used to define the [Document]'s content.
	Content *RecordJSON `json:"content,omitempty"`
	// TextContent is a plaintext representation of the [Document.Content].
	// Should not contain markdown or other formatting.
	TextContent string `json:"textContent,omitempty"`
	// BlueskyPostRef is a strong reference to a Bluesky post.
	// Useful to keep track of comments off-platform.
	//
	// Currently, the type is [any], because I don't understand how I should represent it.
	// It looks like to be a strong ref, but a record generated by `leaflet.pub`:
	//   1. doesn't include a `$type`
	//   2. has more info than required by the lexicon used
	BlueskyPostRef any `json:"bskyPostRef,omitempty"`
	// Tags is an array of strings used to tag or categorize the [Document].
	// Avoid prepending tags with hashtags.
	// Max length: 1280.
	// Max graphemes: 128.
	Tags []string `json:"tags,omitempty"`
	// UpdatedAt is the [time.Time] of the [Document]'s last edit.
	UpdatedAt *time.Time `json:"-"`
}

func (d *Document) Type() string {
	return CollectionDocument
}

func (d *Document) MarshalMap() (map[string]any, error) {
	type t Document
	mp, err := MarshalToMap(t(*d))
	if err != nil {
		return nil, err
	}
	if v, ok := mp["path"]; ok && !strings.HasPrefix(v.(string), "/") {
		mp["path"] = "/" + v.(string)
	}
	mp["publishedAt"] = d.PublishedAt.UTC().Format(TimeFormat)
	if d.UpdatedAt != nil {
		tn := d.UpdatedAt.UTC().Format(TimeFormat)
		mp["updatedAt"] = &tn
	}
	return mp, nil
}

func (d *Document) UnmarshalJSON(b []byte) error {
	type t Document
	var v struct {
		t
		PublishedAt string  `json:"publishedAt"`
		UpdatedAt   *string `json:"updatedAt,omitempty"`
	}
	err := json.Unmarshal(b, &v)
	if err != nil {
		return err
	}
	v.t.PublishedAt, err = ParseTime(v.PublishedAt)
	if err != nil {
		return err
	}
	if v.UpdatedAt != nil {
		v.t.UpdatedAt = new(time.Time)
		*v.t.UpdatedAt, err = ParseTime(*v.UpdatedAt)
		if err != nil {
			return err
		}
	}
	*d = Document(v.t)
	return nil
}

// GetDocumentVerificationTag returns the HTML link tag checked during the verification of the [Document].
func GetDocumentVerificationTag(repo syntax.AtIdentifier, rkey syntax.RecordKey) template.HTML {
	// We don't use /> to end the tag, because it is only valid for HTML5 and only required for XHTML.
	// See https://blog.novalistic.com/archives/2017/08/optional-end-tags-in-html/
	return template.HTML(
		fmt.Sprintf(`<link rel="%s" href="%s">`, CollectionDocument, createAtURI(repo, CollectionDocument, rkey)),
	)
}

// getPublicationVerification returns the string used during the verification of the [Publication].
func getDocumentVerification(repo syntax.AtIdentifier, rkey syntax.RecordKey) string {
	return createAtURI(repo, CollectionDocument, rkey)
}
