package site

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"html/template"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/bluesky-social/indigo/atproto/syntax"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	"golang.org/x/net/html"
)

const CollectionDocument = CollectionBase + ".document"

// Document may be standalone or associated with a [Publication].
// This [Record] can be used to store a document's content and its associated metadata.
type Document struct {
	// Site points to a [Publication] record `at://` or a [Publication.URL] `https://` for loose documents.
	// Avoid trailing slashes.
	Site *URL `json:"site" map:"string"`
	// Title of the [Document].
	// Max length: 5000.
	// Max graphemes: 500.
	Title string `json:"title"`
	// PublishedAt is the [time.Time] of the [Document]'s publish time.
	PublishedAt time.Time `json:"-"`
	// Path is combined with [Document.Site] or [Publication.URL] to construct a canonical URL to the document.
	// A slash should be included at the beginning of this value.
	Path *string `json:"path,omitempty"`
	// A brief Description or excerpt from the [Document].
	// Max length: 30000.
	// Max graphemes: 3000.
	Description *string `json:"description,omitempty"`
	// CoverImage to used for thumbnail or cover.
	// Less than 1MB in size.
	CoverImage *Blob `json:"coverImage,omitempty"`
	// Content is a custom [Record] used to define the [Document]'s content.
	Content *RecordJSON `json:"content,omitempty"`
	// TextContent is a plaintext representation of the [Document.Content].
	// Should not contain markdown or other formatting.
	TextContent string `json:"textContent,omitempty"`
	// BlueskyPostRef is a strong reference to a Bluesky post.
	// Useful to keep track of comments off-platform.
	//
	// Currently, the type is [any], because I don't understand how I should represent it.
	// It looks like to be a strong ref, but a record generated by `leaflet.pub`:
	//   1. doesn't include a `$type`
	//   2. has more info than required by the lexicon used
	BlueskyPostRef any `json:"bskyPostRef,omitempty"`
	// Tags is an array of strings used to tag or categorize the [Document].
	// Avoid prepending tags with hashtags.
	// Max length: 1280.
	// Max graphemes: 128.
	Tags []string `json:"tags,omitempty"`
	// UpdatedAt is the [time.Time] of the [Document]'s last edit.
	UpdatedAt *time.Time `json:"-"`
}

func (d *Document) Type() string {
	return CollectionDocument
}

func (d *Document) MarshalMap() (map[string]any, error) {
	type t Document
	mp, err := MarshalToMap(t(*d))
	if err != nil {
		return nil, err
	}
	if v, ok := mp["path"]; ok && !strings.HasPrefix(v.(string), "/") {
		mp["path"] = "/" + v.(string)
	}
	mp["publishedAt"] = d.PublishedAt.UTC().Format(TimeFormat)
	if d.UpdatedAt != nil {
		tn := d.UpdatedAt.UTC().Format(TimeFormat)
		mp["updatedAt"] = &tn
	}
	return mp, nil
}

func (d *Document) UnmarshalJSON(b []byte) error {
	type t Document
	var v struct {
		t
		PublishedAt string  `json:"publishedAt"`
		UpdatedAt   *string `json:"updatedAt,omitempty"`
	}
	err := json.Unmarshal(b, &v)
	if err != nil {
		return err
	}
	v.t.PublishedAt, err = ParseTime(v.PublishedAt)
	if err != nil {
		return err
	}
	if v.UpdatedAt != nil {
		v.t.UpdatedAt = new(time.Time)
		*v.t.UpdatedAt, err = ParseTime(*v.UpdatedAt)
		if err != nil {
			return err
		}
	}
	*d = Document(v.t)
	return nil
}

// PublicationURL returns the [url.URL] of the linked [Publication].
//
// Prefer using [GetRecord] if you plan to retrieve the record.
// Under the hood, this method retrieves the [Publication] record if [Document.Site] is an [ATURL].
func (d *Document) PublicationURL(ctx context.Context, client lexutil.LexClient) (*url.URL, error) {
	if !d.Site.IsAT() {
		return d.Site.URL(), nil
	}
	at := d.Site.AT()
	pub, err := GetRecord[*Publication](ctx, client, at.Authority(), at.RecordKey())
	if err != nil {
		return nil, err
	}
	return pub.URL, nil
}

var ErrCannotVerifyWithNoPath = errors.New("cannot verify a document with no path")

// Verify the [Document].
func (d *Document) Verify(ctx context.Context, client *http.Client, pubURL *url.URL, repo syntax.AtIdentifier, rkey syntax.RecordKey) (bool, error) {
	if d.Path == nil {
		return false, ErrCannotVerifyWithNoPath
	}
	req, err := http.NewRequest(http.MethodGet, pubURL.String()+*d.Path, nil)
	if err != nil {
		return false, err
	}
	resp, err := client.Do(req.WithContext(ctx))
	if err != nil {
		return false, err
	}
	defer resp.Body.Close()
	doc, err := html.Parse(resp.Body)
	if err != nil {
		return false, err
	}
	for node := range doc.Descendants() {
		if node.Type == html.ElementNode && node.Data == "link" {
			var rel string
			var href string
			for _, attr := range node.Attr {
				switch attr.Key {
				case "rel":
					rel = attr.Val
				case "href":
					href = attr.Val
				}
				if rel != "" && rel != CollectionDocument {
					break
				}
				if href == getDocumentVerification(repo, rkey) {
					return true, nil
				}
			}
		}
	}
	return false, nil
}

// GetDocumentVerificationTag returns the HTML link tag checked during the verification of the [Document].
func GetDocumentVerificationTag(repo syntax.AtIdentifier, rkey syntax.RecordKey) template.HTML {
	// We don't use /> to end the tag, because it is only valid for HTML5 and only required for XHTML.
	// See https://blog.novalistic.com/archives/2017/08/optional-end-tags-in-html/
	return template.HTML(
		fmt.Sprintf(`<link rel="%s" href="%s">`, CollectionDocument, createAtURL(repo, CollectionDocument, rkey)),
	)
}

// getPublicationVerification returns the string used during the verification of the [Publication].
func getDocumentVerification(repo syntax.AtIdentifier, rkey syntax.RecordKey) string {
	return createAtURL(repo, CollectionDocument, rkey).String()
}
